### PR TITLE
Fixes dderevjanik/wsdl-tsclient#15

### PR DESCRIPTION
**Pull request by aesweeting**
Fixes dderevjanik/wsdl-tsclient#15 

Thanks @devyourcar for the original fix suggestion!

### CODE REVIEW

**Comment by dderevjanik** [comment]
Wow, that's really cool..... 
but I'm worried about making Array types also taking non-array type. Is this standard approach in SOAP?

**Comment by aesweeting** [comment]
> but I'm worried about making Array types also taking non-array type. Is this standard approach in SOAP?

I've decided to remove that change as I don't think it's valid in this scenario. Apologies for mixing it in with this PR!

---

A bit of context for anyone interested:

In the case of a `maxOccurs = 1`, I believe `node-soap` transforms the element to an object instead of an array (as per the fix in https://github.com/vpulim/node-soap/pull/1100) in some conditions.

I believe the issue I'm having is likely either a problem with the WSDL I'm integrating with, or with how `node-soap` is parsing the response.

The element is defined as `maxOccurs = unbounded` and I'm receiving one entry in the response XML, which I expect to be transformed to an array, but it is actually an object - which results in the types not matching. In this case, the types are correct and I believe the issue lies elsewhere.

For now, I'm just casting that part of the response as an array until I have time to investigate the problem further.

**Comment by dderevjanik** [comment]
Thank you for explaining that issue. I had several problems with how `node-soap` is parsing WSDL, because of that, I'm planing to replace `node-soap` with forked one... For example, `node-soap` isn't parsing `documentation` element, which could make generated client more usable by adding documentation to jsdoc.

**Comment by devyourcar** [comment]
Great work @aesweeting - although you missed:

1. Adding a new cli option (--outputPascalCase)  (see https://github.com/dderevjanik/wsdl-tsclient/blob/master/src/index.ts#L10)

2. All empty changeCase calls need to pull in the pascalCase option e.g. changeCase(word) -> changeCase(word, {pascalCase: options.pascalCase})

3. All other usages of changeCase with the pascalCase part hard-coded should remain the same.

I think the new release will be breaking, as we've essentially defaulted it to keep the casing. Should probably mention that as part of the release notes.

**Pull request merged**
