### PR TITLE
Fix for code generation types not matching what node-soap produces

### PR DESCRIPTION
**Pull request by nahidakbar**

### CODE REVIEW

**Comment by nahidakbar** [comment]
@cheindl what do I need to do to merge this?

**Comment by cheindl** [comment]
@dderevjanik Would it be possible to merge this request and to make a new release?

**Review by svogl — COMMENTED** [review]
Hi, I tried this patch on a WSDL and it did not work out for me as the data type had a namespace prefix, as in:
          <s:element minOccurs="1" maxOccurs="1" name="DeviceID" type="s:int" />
(s being  xmlns:s="http://www.w3.org/2001/XMLSchema" )

**Comment by ammarnajjar** [comment]
@svogl looks like this PR addresses that issue => https://github.com/dderevjanik/wsdl-tsclient/pull/66

**Pull request merged**
